### ISSUE TITLE
RHEL SSH install user is "install" not "installer"

### ISSUE THREAD

**Issue by justin-davisibm** [IBM/liz#1]
**Describe the bug**
The tool documents the next steps for installing a system as:

"After the installer starts, use an SSH client to connect to the system at the following address:

    SSH host: installer@{{ ip_address }}
"

This should be:
"After the installer starts, use an SSH client to connect to the system at the following address:

    ssh install@{{ ip_address }}
"

RHEL uses "install" as the account, installer will fail.

Suggest also adding the "ssh" command into the copy-able text field

**To Reproduce**
1. Complete your parmfile configuration
2. go to the "next steps" card (https://ibm.github.io/liz/#/expand/nextsteps-card)
3. Follow documentation
4. login fails

**Expected behavior**
Login should succeed (and will if correct user is used).

**Screenshots**

**Additional context**
Excellent tool- really great enhancement to a sometimes obtuse process.

**Comment by modean** [comment]
@justin-davisibm thanks for your feedback. I added the `ssh` command to the code that copies the text snippet to the clipboard.

**Comment by modean** [comment]
Fixed on the latest deployment. https://ibm.github.io/liz/
