### ISSUE TITLE
stealing focus from fields

### ISSUE THREAD

**Issue by mmaslano** [IBM/liz#3]
**Describe the bug**
While filling out `Designate installation source` the focus from field is being stolen. It happened in different fields. Currently, I can't  fill even the first one `Network installation source`.

**To Reproduce**
1. Go to `Designate installation source`
2. Click on: first field and start writing ftp://
3. After every letter focus from field is gone and I need to click in the field, write another  letter, focus is gone, another letter,...

**Expected behavior**
Finishing the parmfile setup.

**Desktop (please complete the following information):**
 - OS: SUSE Tumbleweed
 - Browser chrome
 - Version c61cdc3e77abdd0cb709e8054bb34eedaf7b7a87

**Additional context**
I don't have issues with stealing focus on any other webpage. 

I usually use Firefox, which stopped working on your page (maybe cookies). I was able to finish the parmfile while using it for the first time. It gave me 60 characters for ftp and then the problem with the focus started. I originally wanted to report that even if I pick SUSE at the start, at the end it generates incorrect files for RedHat.

**Comment by modean** [comment]
@mmaslano I confirm that the issue exists and that it can be reproduced. For the time being you might consider typing the URL into a text editor and once done copy it into the text field of the UI. That would you allow to continue composing parm files with that temp workaround until a fix has been made available.

**Comment by mmaslano** [comment]
I can write parmfile ;-) The tool might be interesting for newbies and customers.

**Comment by modean** [comment]
@mmaslano there's a new version available. Can you try this latest deployment (build date: 2024-10-30, commit hash: 45ef6d11d921522e1ef07b31f90a14487cd7efb5) to see whether the focus issue has been solved? Thanks!

**Comment by mmaslano** [comment]
It works now in Chromium. I cleaned cookies in Firefox and it started working too. Looks good!

**Comment by modean** [comment]
@mmaslano thanks! I am closing the issue.
